apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-app
  labels:
    app: ng-app
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: ng-app
  template:
    metadata:
      labels:
        app: ng-app
    spec:
      containers:
      - name: ng-app
        image: ng-app:1.0
        imagePullPolicy: Never
        resources:
          limits:
            cpu: '0.2'
            memory: 0.2G
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ng-app-service
spec:
  selector:
    app: ng-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
